# Generated by Django 4.0.4 on 2022-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=10, verbose_name='Номер критерия для вопроса')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
            ],
        ),
    ]
