# Generated by Django 4.0.4 on 2022-05-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awswer_number', models.CharField(max_length=10, verbose_name='Представление ответа цифрой')),
                ('answer', models.CharField(max_length=500, verbose_name='Ответ')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
            ],
        ),
    ]
